// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModularTemplate.Identity.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModularTemplate.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260615221214_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bondstone.Persistence.EntityFrameworkCore.DomainEvents.DomainEventRecordEntity", b =>
                {
                    b.Property<Guid>("DomainEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("DomainEventId");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CapturedAtUtc");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("CausationId");

                    b.Property<string>("DomainEventName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DomainEventName");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ModuleName");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OccurredAtUtc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Payload");

                    b.Property<string>("PayloadMetadata")
                        .HasColumnType("text")
                        .HasColumnName("PayloadMetadata");

                    b.Property<string>("PayloadTypeName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("PayloadTypeName");

                    b.Property<string>("TraceBaggage")
                        .HasColumnType("text")
                        .HasColumnName("TraceBaggage");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("TraceParent");

                    b.Property<string>("TraceState")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("TraceState");

                    b.HasKey("DomainEventId")
                        .HasName("PK_domain_event_records");

                    b.HasIndex("ModuleName", "CapturedAtUtc");

                    b.HasIndex("ModuleName", "DomainEventName");

                    b.ToTable("domain_event_records", "identity");
                });

            modelBuilder.Entity("Bondstone.Persistence.EntityFrameworkCore.Inbox.InboxMessageEntity", b =>
                {
                    b.Property<string>("ModuleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ModuleName");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("MessageId");

                    b.Property<string>("HandlerIdentity")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("HandlerIdentity");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ProcessedAtUtc");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ReceivedAtUtc");

                    b.HasKey("ModuleName", "MessageId", "HandlerIdentity")
                        .HasName("PK_inbox_messages");

                    b.HasIndex("ReceivedAtUtc");

                    b.ToTable("inbox_messages", "identity");
                });

            modelBuilder.Entity("Bondstone.Persistence.EntityFrameworkCore.IncomingInbox.IncomingInboxMessageEntity", b =>
                {
                    b.Property<string>("ReceiverModule")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ReceiverModule");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("MessageId");

                    b.Property<string>("HandlerIdentity")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("HandlerIdentity");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("AttemptCount");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("CausationId");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ClaimedBy");

                    b.Property<DateTimeOffset?>("ClaimedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ClaimedUntilUtc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<Guid?>("DurableOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("DurableOperationId");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FailedAtUtc");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("FailureReason");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("IngestedAtUtc");

                    b.Property<string>("MessageKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("MessageKind");

                    b.Property<string>("MessageTypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("MessageTypeName");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("Metadata");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NextAttemptAtUtc");

                    b.Property<string>("PartitionKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("PartitionKey");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Payload");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ProcessedAtUtc");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("SourceModule");

                    b.Property<string>("SourceTransportName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("SourceTransportName");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Status");

                    b.Property<string>("TargetModule")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("TargetModule");

                    b.Property<string>("TraceBaggage")
                        .HasColumnType("text")
                        .HasColumnName("TraceBaggage");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("TraceParent");

                    b.Property<string>("TraceState")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("TraceState");

                    b.HasKey("ReceiverModule", "MessageId", "HandlerIdentity")
                        .HasName("PK_incoming_inbox_messages");

                    b.HasIndex("DurableOperationId");

                    b.HasIndex("MessageTypeName");

                    b.HasIndex("SourceTransportName");

                    b.HasIndex("Status", "ClaimedUntilUtc");

                    b.HasIndex("Status", "NextAttemptAtUtc", "IngestedAtUtc");

                    b.HasIndex("ReceiverModule", "Status", "NextAttemptAtUtc", "IngestedAtUtc");

                    b.ToTable("incoming_inbox_messages", "identity");
                });

            modelBuilder.Entity("Bondstone.Persistence.EntityFrameworkCore.Operations.OperationStateEntity", b =>
                {
                    b.Property<Guid>("DurableOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("HandlerIdentity")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("MessageTypeName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ModuleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResultPayload")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DurableOperationId")
                        .HasName("PK_operation_states");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("operation_states", "identity");
                });

            modelBuilder.Entity("Bondstone.Persistence.EntityFrameworkCore.Outbox.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("MessageId");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("AttemptCount");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("CausationId");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ClaimedBy");

                    b.Property<DateTimeOffset?>("ClaimedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ClaimedUntilUtc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DispatchedAtUtc");

                    b.Property<Guid?>("DurableOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("DurableOperationId");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FailedAtUtc");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("FailureReason");

                    b.Property<string>("MessageKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("MessageKind");

                    b.Property<string>("MessageTypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("MessageTypeName");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("Metadata");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NextAttemptAtUtc");

                    b.Property<string>("PartitionKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("PartitionKey");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Payload");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("SourceModule");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Status");

                    b.Property<DateTimeOffset>("StoredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StoredAtUtc");

                    b.Property<string>("TargetModule")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("TargetModule");

                    b.Property<string>("TraceBaggage")
                        .HasColumnType("text")
                        .HasColumnName("TraceBaggage");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("TraceParent");

                    b.Property<string>("TraceState")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("TraceState");

                    b.HasKey("MessageId")
                        .HasName("PK_outbox_messages");

                    b.HasIndex("DurableOperationId");

                    b.HasIndex("MessageTypeName");

                    b.HasIndex("Status", "ClaimedUntilUtc");

                    b.HasIndex("Status", "NextAttemptAtUtc", "StoredAtUtc");

                    b.ToTable("outbox_messages", "identity");
                });

            modelBuilder.Entity("ModularTemplate.Identity.Access.ApplicationAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocalUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocalUserId")
                        .IsUnique();

                    b.ToTable("application_access", "identity");
                });

            modelBuilder.Entity("ModularTemplate.Identity.Users.LocalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique();

                    b.ToTable("local_users", "identity");
                });
#pragma warning restore 612, 618
        }
    }
}
